DSONAME = SOP_Paani.dylib
SOURCES = SOP_Paani.C
# LIBDIRS = ../../Build/Intermediates/paani.build/Debug/paani.build/Objects-normal/x86_64/
# LIBS = utilities.o Particle.o ParticleSystem.o scene.o

include $(HFS)/toolkit/makefiles/Makefile.osx
include $(HFS)/toolkit/makefiles/Makefile.gnu
